-- ============================================================
-- ANÁLISE: MODELAGEM DE ANEXOS DO SISTEMA
-- ============================================================

/*
================================================================================
OPÇÃO A: Tabelas Específicas por Contexto
================================================================================

Prós:
- Simples inicialmente
- FK direta com integridade referencial

Contras:
- Fragmentação de código
- Mesma lógica repetida em várias tabelas
- Dificuldade para consultar anexos globally
- Maintenance overhead crescente
- Schema drift entre tabelas parecidas

Exemplo:
- trx_route_invoice_delivery_attachment
- trx_route_attachment
- trx_vehicle_attachment
- trx_user_attachment
- ... (cresce exponencialmente)

================================================================================
OPÇÃO B: Tabela Genérica Única (RECOMENDADA)
================================================================================

Prós:
- Uma única lógica de upload/download
- Consultas centralizadas
- Schema único para todos os anexos
- Mais fácil manter consistência
- Extensível para novos contextos sem criar tabelas
- Menos código boilerplate
- analytics e relatórios mais simples

Contras:
- entity_type precisa ser bem controlado
- Mais campos (mas compensado pela simplicidade)

================================================================================
DECISÃO: TABELA GENÉRICA - trx_attachment
================================================================================

Justificativa:
1. O sistema já tem múltiplos fluxos de anexo
2.Facilita manutenção e evolução
3.Permite implementar regras de negócio centralizadas
4.Melhor para buscar/filtrar anexos globalmente
5.Escalável para novos contextos sem mudança de schema

================================================================================
*/


-- ============================================================
-- TABELA GENÉRICA DE ANEXOS DO SISTEMA
-- ============================================================

CREATE TABLE IF NOT EXISTS trx_attachment (
    -- Identificação
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Contexto do anexo (entidade pai)
    entity_type VARCHAR(50) NOT NULL,  -- 'route_invoice_delivery', 'route', 'vehicle', 'user', 'fiscal_invoice', 'note', etc.
    entity_id BIGINT NOT NULL,

    -- Tipo de anexo (classificação)
    attachment_type VARCHAR(30) NOT NULL,  -- 'receipt', 'nfd', 'document', 'image', 'signature', 'contract', etc.

    -- Informações do arquivo
    file_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255),  -- Nome original do arquivo antes de renomear
    file_path TEXT NOT NULL,  -- Path interno no storage
    file_url TEXT,  -- URL pública para acesso
    mime_type VARCHAR(100),  -- image/jpeg, application/pdf, etc.
    file_size BIGINT,  -- Tamanho em bytes

    -- Organização
    sort_order INTEGER DEFAULT 0,  -- Ordem de exibição
    description TEXT,  -- Descrição opcional do arquivo

    -- Controle
    is_active BOOLEAN DEFAULT true,
    is_test BOOLEAN DEFAULT false,

    -- Auditoria
    created_by BIGINT,  -- FK para usuário que enviou
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- ÍNDICES PARA PERFORMANCE
-- ============================================================

-- Busca por tipo de entidade
CREATE INDEX idx_attachment_entity ON trx_attachment(entity_type, entity_id);

-- Busca por tipo de anexo dentro de uma entidade
CREATE INDEX idx_attachment_type ON trx_attachment(entity_type, entity_id, attachment_type);

-- Busca por status
CREATE INDEX idx_attachment_active ON trx_attachment(is_active);

-- Busca por quem enviou
CREATE INDEX idx_attachment_created_by ON trx_attachment(created_by);

-- Busca por data de criação
CREATE INDEX idx_attachment_created_at ON trx_attachment(created_at DESC);

-- ============================================================
-- CONSTRAINTS
-- ============================================================

-- Garantir que entity_type seja válido (enum via CHECK)
ALTER TABLE trx_attachment
ADD CONSTRAINT chk_entity_type
CHECK (entity_type IN (
    'route',                    -- Rota
    'route_invoice_delivery',   -- Entrega de nota na rota
    'fiscal_invoice',           -- Nota fiscal
    'vehicle',                  -- Veículo
    'user',                     -- Usuário
    'provider',                 -- Fornecedor
    'customer',                 -- Cliente/Destino
    'route_occurrence',         -- Ocorrência de rota
    'delivery_occurrence'      -- Ocorrência de entrega
));

-- Garantir que attachment_type seja válido
ALTER TABLE trx_attachment
ADD CONSTRAINT chk_attachment_type
CHECK (attachment_type IN (
    'receipt',       -- Canhoto de entrega
    'nfd',          -- NFD/DANFE
    'document',    -- Documento genérico
    'image',       -- Imagem genérica
    'signature',   -- Assinatura
    'contract',    -- Contrato
    'license',     -- Licença/CNH
    'insurance',   -- Seguro
    'inspection',  -- Laudo/Inspeção
    'photo'        -- Foto
));

-- ============================================================
-- HISTÓRICO DE MIGRACIÓN (opcional)
-- ============================================================

/*
CREATE TABLE IF NOT EXISTS trx_attachment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attachment_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL,  -- 'created', 'updated', 'deleted', 'downloaded'
    old_values JSONB,
    new_values JSONB,
    performed_by BIGINT,
    performed_at TIMESTAMPTZ DEFAULT NOW(),
    ip_address VARCHAR(45)
);

CREATE INDEX idx_attachment_history_attachment ON trx_attachment_history(attachment_id);
CREATE INDEX idx_attachment_history_date ON trx_attachment_history(performed_at DESC);
*/

-- ============================================================
-- MAPA DE MIGRAÇÃO DOS FLUXOS ATUAIS
-- ============================================================

/*
================================================================================
MIGRAÇÃO: trx_route_invoice_delivery -> trx_attachment
================================================================================

-- Canhotos (receipt_image_path)
INSERT INTO trx_attachment (
    entity_type,
    entity_id,
    attachment_type,
    file_name,
    file_path,
    is_active,
    is_test,
    created_at,
    updated_at
)
SELECT
    'route_invoice_delivery' as entity_type,
    d.id as entity_id,
    'receipt' as attachment_type,
    COALESCE(SPLIT_PART(d.receipt_image_path, '/', -1), 'canhoto.pdf') as file_name,
    d.receipt_image_path as file_path,
    d.is_active,
    d.is_test,
    COALESCE(d.created_at, NOW()),
    COALESCE(d.updated_at, NOW())
FROM trx_route_invoice_delivery d
WHERE d.receipt_image_path IS NOT NULL
  AND d.receipt_image_path != ''
  AND d.receipt_image_path != '[]';

-- NFDs (nfd_image_path)
INSERT INTO trx_attachment (
    entity_type,
    entity_id,
    attachment_type,
    file_name,
    file_path,
    is_active,
    is_test,
    created_at,
    updated_at
)
SELECT
    'route_invoice_delivery' as entity_type,
    d.id as entity_id,
    'nfd' as attachment_type,
    COALESCE(SPLIT_PART(d.nfd_image_path, '/', -1), 'nfd.pdf') as file_name,
    d.nfd_image_path as file_path,
    d.is_active,
    d.is_test,
    COALESCE(d.created_at, NOW()),
    COALESCE(d.updated_at, NOW())
FROM trx_route_invoice_delivery d
WHERE d.nfd_image_path IS NOT NULL
  AND d.nfd_image_path != ''
  AND d.nfd_image_path != '[]';

================================================================================
EXEMPLOS DE USO FUTURO
================================================================================

-- Buscar todos os canhotos de uma entrega
SELECT * FROM trx_attachment
WHERE entity_type = 'route_invoice_delivery'
  AND entity_id = 123
  AND attachment_type = 'receipt'
  AND is_active = true
ORDER BY sort_order, created_at;

-- Buscar todas as fotos de um veículo
SELECT * FROM trx_attachment
WHERE entity_type = 'vehicle'
  AND entity_id = 456
  AND attachment_type = 'photo'
  AND is_active = true;

-- Contar anexos por tipo no sistema
SELECT
    entity_type,
    attachment_type,
    COUNT(*) as total
FROM trx_attachment
WHERE is_active = true
GROUP BY entity_type, attachment_type
ORDER BY total DESC;
*/

-- ============================================================
-- RESUMO DA PROPOSTA
-- ============================================================

/*
┌─────────────────────────────────────────────────────────────────────────────┐
│                         ESTRUTURA FINAL                                    │
├─────────────────────────────────────────────────────────────────────────────┤
│ TABELA: trx_attachment                                                      │
├─────────────────────────────────────────────────────────────────────────────┤
│ CAMPOS PRINCIPAIS:                                                         │
│ - id: BIGINT (PK)                                                          │
│ - entity_type: VARCHAR(50) -- contexto do anexo (rota, veículo, etc)    │
│ - entity_id: BIGINT -- ID da entidade                                     │
│ - attachment_type: VARCHAR(30) -- tipo (receipt, nfd, photo, etc)         │
│ - file_name: VARCHAR(255) -- nome do arquivo                               │
│ - file_path: TEXT -- path no storage                                      │
│ - file_url: TEXT -- URL pública                                           │
│ - mime_type: VARCHAR(100) -- tipo MIME                                    │
│ - file_size: BIGINT -- tamanho                                             │
│ - sort_order: INTEGER -- ordem                                             │
│ - is_active: BOOLEAN                                                        │
│ - is_test: BOOLEAN                                                          │
│ - created_at/updated_at: TIMESTAMPTZ                                       │
├─────────────────────────────────────────────────────────────────────────────┤
│ RELACIONAMENTO: 1:N (uma entidade pode ter N anexos)                      │
├─────────────────────────────────────────────────────────────────────────────┤
│ ÍNDICES: entity_type+entity_id, attachment_type, is_active               │
└─────────────────────────────────────────────────────────────────────────────┘

VANTAGENS DA TABELA GENÉRICA:
1. Schema único para todos os anexos do sistema
2. Facilidade para adicionar novos tipos de entidade
3. Consultas centralizadas
4. Reutilização de código
5. Analytics simplificado
6. Manutenção reduzida

PRÓXIMOS PASSOS:
1. Executar SQL de criação
2. Migrar dados existentes
3. Ajustar frontend para usar nova estrutura
4. Ajustar serviços de upload/download
5. Remover campos antigos após validação
*/