-- ============================================================
-- TABELA CENTRALIZADA DE ANEXOS DO SISTEMA
-- Execute este SQL para criar a tabela
-- ============================================================

CREATE TABLE IF NOT EXISTS trx_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    attachment_type VARCHAR(30) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_url TEXT,
    mime_type VARCHAR(100),
    file_size BIGINT,
    sort_order INTEGER DEFAULT 0,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    is_test BOOLEAN DEFAULT false,
    created_by BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- ÍNDICES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_attachment_entity ON trx_attachment(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_attachment_type ON trx_attachment(entity_type, entity_id, attachment_type);
CREATE INDEX IF NOT EXISTS idx_attachment_active ON trx_attachment(is_active);
CREATE INDEX IF NOT EXISTS idx_attachment_created_at ON trx_attachment(created_at DESC);

-- ============================================================
-- CHECK CONSTRAINTS
-- ============================================================

ALTER TABLE trx_attachment
ADD CONSTRAINT IF NOT EXISTS chk_entity_type
CHECK (entity_type IN (
    'route', 'route_invoice_delivery', 'fiscal_invoice',
    'vehicle', 'user', 'provider', 'customer',
    'route_occurrence', 'delivery_occurrence'
));

ALTER TABLE trx_attachment
ADD CONSTRAINT IF NOT EXISTS chk_attachment_type
CHECK (attachment_type IN (
    'receipt', 'nfd', 'document', 'image', 'signature',
    'contract', 'license', 'insurance', 'inspection', 'photo'
));