-- ============================================================
-- PROPOSTA DE NORMALIZAÇÃO - Tabela de Anexos de Entrega
-- ============================================================

-- ============================================================
-- 1. CRIAR NOVA TABELA DE ANEXOS
-- ============================================================

CREATE TABLE IF NOT EXISTS trx_route_invoice_delivery_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_route_invoice_delivery BIGINT NOT NULL,
    attachment_type VARCHAR(20) NOT NULL CHECK (attachment_type IN ('receipt', 'nfd')),
    file_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_url TEXT,
    mime_type VARCHAR(100),
    file_size BIGINT,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    is_test BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 2. CRIAR ÍNDICES PARA PERFORMANCE
-- ============================================================

CREATE INDEX idx_attachment_delivery ON trx_route_invoice_delivery_attachment(id_route_invoice_delivery);
CREATE INDEX idx_attachment_type ON trx_route_invoice_delivery_attachment(attachment_type);
CREATE INDEX idx_attachment_active ON trx_route_invoice_delivery_attachment(is_active);

-- ============================================================
-- 3. CRIAR FOREIGN KEY
-- ============================================================

ALTER TABLE trx_route_invoice_delivery_attachment
ADD CONSTRAINT fk_attachment_delivery
FOREIGN KEY (id_route_invoice_delivery)
REFERENCES trx_route_invoice_delivery(id)
ON DELETE CASCADE;

-- ============================================================
-- 4. O QUE FAZER COM OS CAMPOS ANTIGOS
-- ============================================================

/*
OPÇÃO A: Migrar dados existentes para nova tabela (RECOMENDADO)

-- Migração de receipt_image_path (Canhoto)
INSERT INTO trx_route_invoice_delivery_attachment (
    id_route_invoice_delivery,
    attachment_type,
    file_name,
    file_path,
    is_active,
    is_test,
    created_at,
    updated_at
)
SELECT
    id,
    'receipt',
    COALESCE(SPLIT_PART(receipt_image_path, '/', -1), 'canhoto'),
    receipt_image_path,
    is_active,
    is_test,
    COALESCE(created_at, NOW()),
    COALESCE(updated_at, NOW())
FROM trx_route_invoice_delivery
WHERE receipt_image_path IS NOT NULL
  AND receipt_image_path != ''
  AND receipt_image_path != '[]';

-- Migração de nfd_image_path (NFD)
INSERT INTO trx_route_invoice_delivery_attachment (
    id_route_invoice_delivery,
    attachment_type,
    file_name,
    file_path,
    is_active,
    is_test,
    created_at,
    updated_at
)
SELECT
    id,
    'nfd',
    COALESCE(SPLIT_PART(nfd_image_path, '/', -1), 'nfd'),
    nfd_image_path,
    is_active,
    is_test,
    COALESCE(created_at, NOW()),
    COALESCE(updated_at, NOW())
FROM trx_route_invoice_delivery
WHERE nfd_image_path IS NOT NULL
  AND nfd_image_path != ''
  AND nfd_image_path != '[]';

-- OPÇÃO B: Manter campos antigos como legado (apenas leitura)
-- Não fazer nada, manter os campos para compatibilidade

-- OPÇÃO C: Remover campos antigos (após migração completa)
-- ALTER TABLE trx_route_invoice_delivery DROP COLUMN receipt_image_path;
-- ALTER TABLE trx_route_invoice_delivery DROP COLUMN nfd_image_path;
*/

-- ============================================================
-- 5. CONSULTAS DE EXEMPLO
-- ============================================================

/*
-- Buscar todos os canhotos de uma entrega
SELECT * FROM trx_route_invoice_delivery_attachment
WHERE id_route_invoice_delivery = 123
  AND attachment_type = 'receipt'
  AND is_active = true
ORDER BY sort_order, created_at;

-- Buscar todos os NFDs de uma entrega
SELECT * FROM trx_route_invoice_delivery_attachment
WHERE id_route_invoice_delivery = 123
  AND attachment_type = 'nfd'
  AND is_active = true
ORDER BY sort_order, created_at;

-- Contar anexos por tipo
SELECT
    id_route_invoice_delivery,
    attachment_type,
    COUNT(*) as total
FROM trx_route_invoice_delivery_attachment
WHERE is_active = true
GROUP BY id_route_invoice_delivery, attachment_type;
*/

-- ============================================================
-- RESUMO DA PROPOSTA
-- ============================================================

/*
Tabela Principal:
- trx_route_invoice_delivery (resultados de entrega - já existe)

Nova Tabela:
- trx_route_invoice_delivery_attachment (anexos múltiplos)

Relacionamento:
- 1 delivery pode ter N anexos (1:N)

Campos da nova tabela:
- id: chave primária
- id_route_invoice_delivery: FK para trx_route_invoice_delivery
- attachment_type: 'receipt' (canhoto) ou 'nfd'
- file_name: nome original do arquivo
- file_path: path no storage
- file_url: URL pública (opcional)
- mime_type: tipo MIME do arquivo
- file_size: tamanho em bytes
- sort_order: ordem de exibição
- is_active: soft delete
- is_test: ambiente de teste
- created_at/updated_at: auditoria
*/